@API_HostAddress = http://localhost:5023

POST {{API_HostAddress}}/api/orders/quote
Content-Type: application/json
Accept: application/json
{
  "items": [
    { "productId": "abc", "unitPrice": 25.0, "quantity": 2 }
  ],
  "couponCode": "SAVE10"
}

###
